### ISSUE TITLE
does not work with https endpoints

### ISSUE THREAD

**Issue by zhelyan** [tabeyti/jenkins-jack#1]
because of hardcoded gsub of `http://`

**Comment by tabeyti** [comment]
This will be fixed in the next release. A setting/option for disabling strict TLS will be made available (disabled by default), along with better parsing of the Jenkins URI setting, allowing the inclusion of the protocol and such (http/https).

**Comment by tabeyti** [comment]
Fixed in [0.1.4](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#014)
