### ISSUE TITLE
Jenkins:job.create: forbidden 

### ISSUE THREAD

**Issue by dNodal0** [tabeyti/jenkins-jack#17]
Hello,
I do not have the rights on the root of jenkins, suddenly, I cannot create a job, is it possible to specify a directory ?

I have this error: Jenkins:job.create: forbidden 

Regards,

**Comment by mkaurin** [comment]
Looks like the `.Jenkinsfile.config.json` is not respected for me when i try to change the name there

**Comment by whatarule** [comment]
This worked for me.
- set jenkins api token string to password value in setting.json

**Comment by tabeyti** [comment]
Hey @dNodal0 ,

Sounds like a permissions issue for the extension to write out the `.<your_script>.config.json` for your local script. Currently the config is created at the same directory as the script when you execute a Pipeline.

The ability to specify a directory for saving the config file sounds like an enhancement, so I'm going to flag this issue as such so it can be looked at for the next update.

**Comment by dNodal0** [comment]
Thank you.
