### ISSUE TITLE
[Query] command 'extension.jenkins-jack.jacks' not found

### ISSUE THREAD

**Issue by vrenjith** [tabeyti/jenkins-jack#19]
Hi,
I just installed the latest version of Jenkins Jack (v 1.0.1) in VS Code Version: 1.43.1
I am getting the same error reported in #8 

I am sure this is a resolved issue and I am doing something wrong here. Do we need an installation of groovy needed in the machine to use this extension? Or is there anything else I am missing @tabeyti ?

-Renjith

**Comment by sboardwell** [comment]
Experiencing the same thing. None of the commands can be found apparently.

```shell
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic snap
```

Tried different versions of jenkins-jack. All had the same problem.

**Comment by tabeyti** [comment]
Hey @vrenjith and @sboardwell 

Super sorry for such a late reply to this. The latest version [1.1.0 should have fixed this](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#fixed).

Ensure your extension is updated, and If one of you could please validate for me, I'd appreciate it.

**Comment by sboardwell** [comment]
@tabeyti - works great, thanks for the fix!

**Comment by deuxksy** [comment]
Hi, I'm using jenkins-jack very well, thank you. 
Recently, I encountered the same bug and can't use it.
I am using vscode remotely.
The client is windows 11 and the server is mac studio.

> Version: 1.91.1 (user setup)
> Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
> Date: 2024-07-09T22:06:49.809Z
> Electron: 29.4.0
> ElectronBuildId: 9728852
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Windows_NT x64 10.0.26100

![01](https://github.com/user-attachments/assets/4f1f792e-5074-4081-9c43-c60fd34d66bd)
