### ISSUE TITLE
how to create pipeline in a folder?

### ISSUE THREAD

**Issue by daty2141** [tabeyti/jenkins-jack#2]
i have folder plugin installed in my jenkins,and this extension can't create pipeline in the folder.

**Comment by tabeyti** [comment]
Hey @daty2141 . Sorry for the late reply. 

Currently, there is no support for the folder extension in respect to creating/running Pipeline scripts.

The extension doesn't have a way of tying a groovy file to a folder hierarchy in Jenkins. 

Off the top of my head, I'm unable to think of an easy way of doing this that doesn't involve creating a vscode 'workspace' type setup where workspace settings are saved to store this information (something I want down the road).

**Comment by Theldris** [comment]
Hi,
I was looking into this and I finally used the "name" from the configuration file when defining the job name in the pipelineJack.ts file which seems to be working correctly.

I'm don't see where the 'name' property from the config file is currently used ? I thought this could be a good use, I could try to make a pull request if needed.

**Comment by SVilgelm** [comment]
Please add support for the folders.

**Comment by mushon4** [comment]
also waiting for this... :) thanks

**Comment by MilanMasek** [comment]
+1

**Comment by chkania** [comment]
+1

**Comment by GoaMind** [comment]
+1

**Comment by tabeyti** [comment]
Sorry for the super late follow up on this. [Version 1.10 now supports this feature](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#pipeline-jack).
