### ISSUE TITLE
Fetch and open pipeline groovy script for edit.

### ISSUE THREAD

**Issue by ethsw** [tabeyti/jenkins-jack#27]
Except of currently supported execution and update of pipeline script, it would be amazing to fetch and open pipeline groovy script directly from the server. Select it from the list of all available jobs on the server in VS and after selection show it in the editor, make appropriate changes and push it back.

**Comment by tabeyti** [comment]
You read my mind @ethsw . You read...my mind...

Check version 1.1.0. The new [Pipeline view](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#pipeline-view) supports pulling scripts from jobs configs and build replays.
