### ISSUE TITLE
option to hide pipeline output

### ISSUE THREAD

**Issue by Inetov** [tabeyti/jenkins-jack#30]
pipeline output lines are often useless.
but it takes up useful space, see screenshot: 8 of 13 lines are not interesting to me. I think it's not only for me.
it would be nice to make an option to turn off the "green" lines so that they are not displayed at all.

![изображение](https://user-images.githubusercontent.com/45286374/92303618-496d3400-ef7f-11ea-8cab-c768032569be.png)

**Comment by tabeyti** [comment]
Hey @Inetov ,

I'm going to mark this as an enhancement, possibly slate it for the next release.

FYI, you can actually suppress the Pipeline output using a combination of the Simple Theme plugin and a few lines of CSS:

https://issues.jenkins-ci.org/browse/JENKINS-41845?focusedCommentId=386998&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-386998

**Comment by Inetov** [comment]
> FYI, you can actually suppress the Pipeline output using a combination of the Simple Theme plugin and a few lines of CSS:

Thanks I know. But this way does not affect what is displayed in vscode output window.

**Comment by tabeyti** [comment]
Word. This is slated for the next release. Change is already in `master`:
https://github.com/tabeyti/jenkins-jack/commit/f698ad58f9ccf3599e1f086f3f2102eb5022d23d

**Comment by tabeyti** [comment]
Hey @Inetov ,

This setting has been added to [version 1.1.1](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#features).  If you could update your extensions version and validate for me, I'd appreciate it.

**Comment by Inetov** [comment]
> 
> 
> Hey @Inetov ,
> 
> This setting has been added to [version 1.1.1](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#features). If you could update your extensions version and validate for me, I'd appreciate it.

works as expected! thank you! I think you can close it)

**Comment by tabeyti** [comment]
Sweet!
