### ISSUE TITLE
Can't execute and update jobs

### ISSUE THREAD

**Issue by leonshklyar** [tabeyti/jenkins-jack#38]
I'm running jenkins in docker (using mac os) version 2.249, I can see my jobs and even link scrip to a job.
Job update/execution fails with message :
"Error running command extension.jenkins-jack.pipeline.execute: jenkins: job.config: forbidden. This is likely caused by the extension that contributes extension.jenkins-jack.pipeline.execute."

Looks like this is due to Jenkins improvement of the CSRF protection feature

**Comment by leonshklyar** [comment]
Jenkins 2.222.1 : 

Always enabled CSRF Protection
Jenkins will automatically enable CSRF protection with the default crumb issuer if it was disabled before. The ability to not have CSRF protection enabled has been deprecated and removed from the UI.

API clients should authenticate using API tokens, which doesn’t require CSRF crumbs since 2.96.

**Comment by tabeyti** [comment]
Hey @leonshklyar ,

This should now be [fixed in 1.1.1](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#fixed). If you could update the extension and validate for me, I'd appreciate it.
