### ISSUE TITLE
Could not connect to the remote Jenkins

### ISSUE THREAD

**Issue by Inetov** [tabeyti/jenkins-jack#43]
Can't execute pipeline with message "Could not connect to the remote Jenkins" but NODES update correctly.
vs-code: 1.51.1
Jenkins Jack: 1.1.1
![изображение](https://user-images.githubusercontent.com/45286374/101394360-73fdbe80-38d9-11eb-8872-99f88fcfd5fc.png)

**Comment by tabeyti** [comment]
Hey @Inetov,

This may be a bug mentioned in a few others issues that was introduced with 1.1.1.

I've put in a fix and created a `.vsix` extension file I'd like you try. Just unzip the file and follow these instructions on how to install the `.vsix`.

If this fixes things, I will put out an update as soon as a I can, hopefully today.
[jenkins-jack-0.0.0.vsix.zip](https://github.com/tabeyti/jenkins-jack/files/5654940/jenkins-jack-0.0.0.vsix.zip)

**Comment by MathieuJouis** [comment]
Hello @tabeyti,
I have the same issue.
The installation of the vsix solved the problem.

**Comment by tabeyti** [comment]
Thank you @MathieuJouis. Fix has been published under [1.1.2](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#fixes). 

Once someone has updated to 1.1.1 and validated things are okay. I'll close this issue off.

**Comment by MathieuJouis** [comment]
Hello @tabeyti ,
For me it's ok after upgrading to 1.1.2.
Thank you !

**Comment by Inetov** [comment]
@tabeyti
version 1.1.2, it's work!
thank you!
