### ISSUE TITLE
"Jenkins Jack: Could not connect to the remote Jenkins"

### ISSUE THREAD

**Issue by ishepherd** [tabeyti/jenkins-jack#5]
How do I troubleshoot "Could not connect"?

-------
1. `Jenkins-jack > Jenkins: Uri` = `https://myhost`

Developer tools console:

> Using the following URI for Jenkins client: http://myusername:mytoken@https://myhost

Seems it doesn't support URIs in the Uri setting

------

2. `Jenkins-jack > Jenkins: Uri` = `myhost`

Developer tools console:

> Using the following URI for Jenkins client: http://myusername:mytoken@myhost

Still the same notification "Could not connect to the remote Jenkins"

When I try that URI in a web browser, the company Jenkins server sends back a 307 redirect to the https:// version. Maybe the extension doesn't like the redirect?

**Comment by tabeyti** [comment]
Latest version [0.1.4](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#014) now supports better parsing for URIs and should fix this issue.

There is also a setting to disable strict TLS for endpoints without valid certs.

**Comment by kamalbaldawa** [comment]
I am also facing the above issue

rror running command extension. Jenkins-jack.tree.connections.refresh: Cannot read properties of undefined (reading 'connection'). This is likely caused by the extension that contributes extension.jenkins-jack.tree.connections.refresh.

**Comment by neljo8m** [comment]
I am also seeing this issue.
It has been working fine for months, up until a few weeks ago.
VS Code v1.80.2
Jenkins Jack v1.2.1
MacOS Ventura 13.4.1
